title: A-Frame-Projekt
description: Moderne Adaption der dritten Szene aus Bertolt Brechts Theaterst√ºck 'Der gute Mensch von Sezuan'
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
